name: Codacy Coverage Reporter

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install setuptools

      - name: Run tests
        run: |
          pytest --cov-report term --cov=cargo_shipping tests/ --cov-report xml

  test-codacy-coverage:
    needs: test
    runs-on: ubuntu-latest
    name: upload-coverage-to-codacy
    steps:
      - name: Upload coverage file
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml

  # codacy-coverage-reporter:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   name: codacy-coverage-reporter
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Run codacy-coverage-reporter
  #       uses: codacy/codacy-coverage-reporter-action@master
  #       with:
  #         # repository > settings > secrets and variables > actions > new repository secret
  #         api-token: ${{ secrets.CODACY_API_TOKEN }}
  #         coverage-reports: coverage.xml
