name: Cargo Shipping App Workflow

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install setuptools

      - name: Run tests
        run: |
          pytest --cov-report term --cov=cargo_shipping tests/ --cov-report xml

      - name: Upload coverage report to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
        run : |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
